### ISSUE TITLE
extract.docx Bug: First item in bulleted list repeated

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#1]
I have noticed a situation where the first item in a bulleted list incorrectly gets doubled in the XML output. You can see this in the attached part2c word document and generated XML. Search for “positive cache control” or "as-is" in both files and you’ll see the problem.

Note that `<list> `has been deprecated, and we probably should use `<ul>, <ol> or  <dl> `instead.

[draft-cdni-cache-control-metadata-00 (2).txt](https://github.com/streaming-video-technology-alliance/tool-gdoc2rfc/files/12621750/draft-cdni-cache-control-metadata-00.2.txt)
[part2c.docx](https://github.com/streaming-video-technology-alliance/tool-gdoc2rfc/files/12621752/part2c.docx)

**Comment by alfonsosiloniz** [comment]
New extract_html.py has solved that problem
