### ISSUE TITLE
extract_html.py BUG: part2i, most of the JSON examples truncated

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#10]
most of the JSON examples come across with only the first line (a single curly brace), with the rest of the example gone.

**Comment by alfonsosiloniz** [comment]
Fixed.

This draft had a different HTML structure for code blocks. Instead of having only 1 <p> tag in the <td>, this draft has multiple <p> tags inside the <td>

Now the code covers both situations.
