### ISSUE TITLE
New Feature: possibility to generate internal references

### ISSUE THREAD

**Issue by alfonsosiloniz** [streaming-video-technology-alliance/tool-gdoc2rfc#12]
Some comments from Kevin Ma in part 2f is to include the internal references to other objects in the same draft.

We need to look a way to refer this in the GDOC than can be converted to xlinks in the RFC XML

**Comment by glenng1215gh** [comment]
I tested this and it is not always picking up the internal references and converting them. In parts 2c and 2i, search for the word "see" and you will find various examples.

**Comment by alfonsosiloniz** [comment]
Yes, it was only doing it for lists. Now it does in the whole document paragraphs. I've updated all the drafts with this version.
