### ISSUE TITLE
extract_docx: Bulleted Lists should not be numbered

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#2]
Bulleted lists from the google doc should always come across as unordered lists in the generated XML.  You can see this in the bulleted list referenced in the repeated first list item bug.

`<list> `has been deprecated, and we probably should use `<ul>, <ol> or  <dl> `instead.

**Comment by alfonsosiloniz** [comment]
The new extract_html only uses and generates <ul>
