### ISSUE TITLE
rfc_format.xml: table of contents depth is always 4

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#6]
changing `<?rfc tocdepth="5"?>` doesn't have any effect. Part 2b, for example, needs a depth of 5, but we always seem to get 4. cahnging tocdepth to a smaller number (like 2), still renders a Table of Contents with depth of 4.

**Comment by alfonsosiloniz** [comment]
You're right. The generate_rfc is not generating correctly the XML because it is stripping out the declaration and processing instructtions. Working on it

**Comment by alfonsosiloniz** [comment]
this is fixed. Now the configuration attributes in the xml are considered when uploading the xml
