### ISSUE TITLE
extract_html.py BUG: entire bulleted lists get dropped (part2c and part2i examples)

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#8]
part2c: take a look after this bit of text "The enumerated options for internal and external cache policies are defined as follows:". the bulleted list of 3 items (as-is, no-cache, and no-store) got dropped.

part2i: take a look after this bit of text  "Consideration is needed when addressing key rollover, expiration, and revocation in the embedded model. The RECOMMENDED workflow for key rollover is as follows:". bulleted list after this gets dropped.

**Comment by alfonsosiloniz** [comment]
@glenng1215gh the problem with the bullet section is that is not following the same style for bullets than the rest of the document.

We should be sure the styling is consistent. I think we should include a rule about format of bullets in the Authoring guide.
