### ISSUE TITLE
extract_html.py BUG: extra characters added to some lines

### ISSUE THREAD

**Issue by glenng1215gh** [streaming-video-technology-alliance/tool-gdoc2rfc#9]
in part2c, the output has this extra [a][b] added.

search for these examples in part2c:

 Mandatory-to-Specify: No. The default is “as-is”.**[a][b]**
3.3.  MI.StaleContentCachePolicy[e][f]

**Comment by alfonsosiloniz** [comment]
The letters between brackets are GDOC comments, that appear in the HTML format as links to the bottom of the page. Now the tool will rip those references to comments"
